#!/usr/bin/env bash

# update the submodules
echo Updating submodules
git pull
git submodule update --init --recursive
git submodule foreach git checkout -f master
git submodule foreach git pull

# determine if custom template repo in use
source /etc/atl

if [[ -n "${ATL_CUSTOM_TEMPLATE_REPO}" ]]; then
    # apply git key if entered
    if [[ -n "${ATL_CUSTOM_TEMPLATE_GITKEY}" ]]; then
        sshlocation=/home/forge/.ssh
        gitkeylocation=$sshlocation/gitkey
        gitkey=$(aws --region=${ATL_AWS_REGION} ssm get-parameters --names "${ATL_CUSTOM_TEMPLATE_GITKEY}" --with-decryption | jq --raw-output '.Parameters[0] .Value')
        chmod 770 $sshlocation
        echo -e $gitkey > $gitkeylocation
        chmod 700 $sshlocation
        chmod 600 $gitkeylocation
        export GIT_SSH_COMMAND="ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i $gitkeylocation"
    fi
    # update the repo from master
    echo Updating custom-templates
    cd /home/forge/custom-templates/*/.
    echo Updating $PWD from master
    git checkout -f master
    git pull
fi